### ISSUE TITLE
Boolean support?

### ISSUE THREAD

**Issue by edcolmar** [mrxmamun/flask-mvc-pymongo#1]
Hello.  Thanks for this! 

What is required to support boolean values?

**Comment by akmamun** [comment]
Could you explain more about the question?

**Comment by edcolmar** [comment]
In /src/factory/validation you have support for string, int, etc...  What would be required to include boolean values?

**Comment by akmamun** [comment]
To add support for boolean values in the validate_type function, you can simply add the following line:
`
elif desired_type == "bool":
    return type(element) == bool`

**Comment by edcolmar** [comment]
ty
